name: CI Workflows

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
